### PR TITLE
Streamlining Survey Data Passing Between Components

### LINKED ISSUE #32: [Frontend] Streamlining Data Passage Between Components
### Pre-flight checklist

- [x] I have searched the existing issues
- [x] I have read the contributing guidelines

### Describe the bug

Currently the way we are passing integral information (like employe ID or survey referral code) between react components is very unreliable. The "useEffect" does not properly initialize important fields (like referral code), and while there are work arounds for this bug, the entire process should probably be streamlined. 

There are different processes for transferring data with a QR code and a typed referral code, which provides a level of inconsistency and unreliability. A QR code will provide a redirect and store parameters in the URL, while a typed referral code uses the react hook "useLocation".  I suspect there are bugs with the QR code route too.

### Steps to reproduce

1. Navigate to "add new entry page" 
2. Enter a referral code 
3. If useEffect is used to set this refferal code, the "refferedByCode" will always be set to null, even though it should not be null
*while this can be fixed, the process should still be streamlined with QR code

### Expected behavior

referredByCode is supposed to be non-null after a referral code is entered. 

### Relevant log output / screenshots

```shell

```

### Software version

v1

### Environment

None

### Other environment details

_No response_

### PR DESCRIPTION
**Pull request by hana-amos**
## 📄 Description

Addresses issue #32 by creating a Zustand store to persist certain survey data, preventing values like referral codes and employee IDs from being lost (null/empty) on refresh. Now referral codes are passed consistently from both typed input and QR scans, and corrects the missing ?ref=code query parameter in the URL.

All instances of data passage that use localStorage are handled by the backend `authTokenHandler` and confined to that one file. It standardizes and centralizes the storage and retrieval of authentication-related data.

## ✅ Checklist

- [ ] Tests added/updated where needed
- [ ] Docs added/updated if applicable
- [X] I have linked the issue this PR closes (if any)

## 🔗 Related Issues

Resolves #32 

## 💡 Type of change

| Type            | Checked? |
|-----------------|----------|
| 🐞 Bug fix      | [X] |
| ✨ New feature   | [ ] |
| 📝 Documentation | [ ] |
| ♻️ Refactor      | [ ] |
| 🛠️ Build/CI      | [ ] |
| Other (explain) | [ ] |

## 🧪 How to test

1. Click the (+) icon in the top right and navigate to "Apply Referral Code" page.
2. Enter your referral code to start the survey.
3. Complete the survey (you can also refresh multiple times to test if the values persist despite refreshing). To end the survey quickly, answer that you are under 18 in the prescreening section.
4. When viewing past survey entries, you should be able to see the employee ID, name, referral code, etc. all be non-null and populated with the correct data.

Survey run-through

https://github.com/user-attachments/assets/f2c97a0a-43f1-4dff-ac99-9d66f3cfef44

Logout run-through

https://github.com/user-attachments/assets/3d71b4ca-c2f3-4405-9bfd-66770876363c

## 📝 Notes to reviewers

N/A

### CODE REVIEW

File: client/src/pages/QRCodeScan&Referral/ApplyReferral.tsx [hunk 1]
```diff
@@ -133,6 +133,7 @@ export default function ApplyReferral({ onLogout }: LogoutProps) {
 				setLoading(false);
 				return;
 			}
+			navigate(`/survey?ref=${referralCode}`);
```
Comment (anantmittal) [inline client/src/pages/QRCodeScan&Referral/ApplyReferral.tsx:136]: @hana-amos: Could you explain this decision/

**Review by anantmittal — COMMENTED** [review]
@hana-amos Left a comment for your response.
